name: final_project
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.4
  - matplotlib=3.7.1
  - imageio=2.19.3
  - numpy=1.24.3
  - scikit-image=0.20.0
  - dill=0.3.7
  - cpuonly
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - torchvision=0.13.1

  
